import 'package:sqflite/sqflite.dart';
import 'package:url_launcher/url_launcher.dart';

import '../database/app_database.dart';

class WhatsAppShare {
  WhatsAppShare._();

  static String money(dynamic value) {
    final n=value is num ? value.toDouble() : double.tryParse('$value')??0;
    return n.toStringAsFixed(2);
  }

  static String _phoneDigits(String? phone) {
    if(phone==null) return '';
    return phone.replaceAll(RegExp(r'[^0-9]'),'');
  }

  static Future<void> send(String text,{String? phone}) async {
    final digits=_phoneDigits(phone);
    final uri=Uri.https('wa.me',digits,{'text':text});
    final ok=await launchUrl(uri,mode:LaunchMode.externalApplication);
    if(!ok) {
      throw StateError('WhatsApp could not be opened on this device.');
    }
  }

  static Future<void> shareSalesmanCredit(Map<String,Object?> salesman) async {
    final Database db=await AppDatabase.instance.database;
    final id='\${salesman['id']}';
    final sales=await db.rawQuery(
      'SELECT invoice_no,total,paid,due,created_at FROM sales WHERE salesman_id=? ORDER BY created_at DESC LIMIT 20',
      [id],
    );
    final totals=await db.rawQuery(
      'SELECT COALESCE(SUM(total),0) total,COALESCE(SUM(paid),0) paid,COALESCE(SUM(due),0) due FROM sales WHERE salesman_id=?',
      [id],
    );
    final t=totals.first;
    final b=StringBuffer()
      ..writeln('QAMVIO POS — Salesman Credit Statement')
      ..writeln('Salesman: \${salesman['name']??''}')
      ..writeln('Phone: \${salesman['phone']??''}')
      ..writeln('Total sales: \${money(t['total'])}')
      ..writeln('Received: \${money(t['paid'])}')
      ..writeln('Outstanding credit: \${money(t['due'])}')
      ..writeln();

    if(sales.isEmpty) {
      b.writeln('No credit invoices found.');
    } else {
      b.writeln('Recent invoices:');
      for(final row in sales) {
        b.writeln(
          '• \${row['invoice_no']} | \${row['created_at']} | '
          'Total \${money(row['total'])} | Paid \${money(row['paid'])} | Due \${money(row['due'])}',
        );
      }
    }
    b.writeln();
    b.writeln('Generated by QAMVIO POS');
    await send(b.toString(),phone:salesman['phone']?.toString());
  }

  static Future<void> shareSupplierCredit(Map<String,Object?> supplier) async {
    final Database db=await AppDatabase.instance.database;
    final id='\${supplier['id']}';
    final purchases=await db.rawQuery(
      'SELECT total,paid,due,created_at FROM purchases WHERE supplier_id=? ORDER BY created_at DESC LIMIT 20',
      [id],
    );
    final totals=await db.rawQuery(
      'SELECT COALESCE(SUM(total),0) total,COALESCE(SUM(paid),0) paid,COALESCE(SUM(due),0) due FROM purchases WHERE supplier_id=?',
      [id],
    );
    final t=totals.first;
    final b=StringBuffer()
      ..writeln('QAMVIO POS — Supplier Credit Statement')
      ..writeln('Supplier: \${supplier['name']??''}')
      ..writeln('Phone: \${supplier['phone']??''}')
      ..writeln('Account balance: \${money(supplier['balance'])}')
      ..writeln('Purchases: \${money(t['total'])}')
      ..writeln('Paid: \${money(t['paid'])}')
      ..writeln('Purchase due: \${money(t['due'])}')
      ..writeln();

    if(purchases.isEmpty) {
      b.writeln('No purchase credit records found.');
    } else {
      b.writeln('Recent purchases:');
      for(final row in purchases) {
        b.writeln(
          '• \${row['created_at']} | Total \${money(row['total'])} | '
          'Paid \${money(row['paid'])} | Due \${money(row['due'])}',
        );
      }
    }
    b.writeln();
    b.writeln('Generated by QAMVIO POS');
    await send(b.toString(),phone:supplier['phone']?.toString());
  }

  static Future<void> shareInvoice(Map<String,Object?> sale) async {
    final Database db=await AppDatabase.instance.database;
    final id='\${sale['id']}';
    final items=await db.query(
      'sale_items',
      where:'sale_id=?',
      whereArgs:[id],
      orderBy:'id',
    );

    Map<String,Object?>? customer;
    final customerId=sale['customer_id']?.toString();
    if(customerId!=null && customerId.isNotEmpty) {
      final rows=await db.query(
        'customers',
        where:'id=?',
        whereArgs:[customerId],
        limit:1,
      );
      if(rows.isNotEmpty) customer=rows.first;
    }

    final b=StringBuffer()
      ..writeln('QAMVIO POS — Sales Invoice')
      ..writeln('Invoice: \${sale['invoice_no']??''}')
      ..writeln('Date: \${sale['created_at']??''}');

    if(customer!=null) {
      b.writeln('Customer: \${customer['name']??''}');
      if('\${customer['phone']??''}'.trim().isNotEmpty) {
        b.writeln('Phone: \${customer['phone']}');
      }
    }

    b.writeln();
    b.writeln('Items:');
    for(final item in items) {
      b.writeln(
        '• \${item['product_name']} × \${money(item['qty'])} @ '
        '\${money(item['price'])} = \${money(item['total'])}',
      );
    }

    b
      ..writeln()
      ..writeln('Subtotal: \${money(sale['subtotal'])}')
      ..writeln('Discount: \${money(sale['discount'])}')
      ..writeln('Total: \${money(sale['total'])}')
      ..writeln('Paid: \${money(sale['paid'])}')
      ..writeln('Due: \${money(sale['due'])}')
      ..writeln()
      ..writeln('Thank you — QAMVIO POS');

    await send(b.toString(),phone:customer?['phone']?.toString());
  }

  static Future<void> shareBusinessReport() async {
    final Database db=await AppDatabase.instance.database;
    final x=await AppDatabase.instance.extendedReportTotals();
    final dashboard=await AppDatabase.instance.dashboardTotals();

    Future<double> scalar(String sql) async {
      final rows=await db.rawQuery(sql);
      return (rows.first.values.first as num?)?.toDouble()??0;
    }

    final customerBalance=await scalar(
      'SELECT COALESCE(SUM(balance),0) FROM customers',
    );
    final supplierBalance=await scalar(
      'SELECT COALESCE(SUM(balance),0) FROM suppliers',
    );
    final salesmanDue=await scalar(
      'SELECT COALESCE(SUM(due),0) FROM sales WHERE salesman_id IS NOT NULL',
    );

    final b=StringBuffer()
      ..writeln('QAMVIO POS — Full Business Report')
      ..writeln('Generated: \${DateTime.now().toLocal()}')
      ..writeln()
      ..writeln('Sales: \${money(x['sales'])}')
      ..writeln('Purchases: \${money(x['purchases'])}')
      ..writeln('Expenses: \${money(x['expenses'])}')
      ..writeln('Profit estimate: \${money(x['profit'])}')
      ..writeln()
      ..writeln('Customer receivables: \${money(customerBalance)}')
      ..writeln('Sales invoice due: \${money(x['due'])}')
      ..writeln('Salesman credit due: \${money(salesmanDue)}')
      ..writeln('Supplier payable balance: \${money(supplierBalance)}')
      ..writeln('Supplier purchase due: \${money(x['supplierDue'])}')
      ..writeln()
      ..writeln('Inventory cost value: \${money(x['stockCost'])}')
      ..writeln('Inventory sale value: \${money(x['stockRetail'])}')
      ..writeln('Products: \${dashboard['products']??0}')
      ..writeln('Customers: \${dashboard['customers']??0}')
      ..writeln()
      ..writeln('Generated by QAMVIO POS');

    await send(b.toString());
  }
}
