import 'package:sqflite_sqlcipher/sqflite.dart';
import 'package:url_launcher/url_launcher.dart';

import '../database/app_database.dart';
import '../localization/localized_text.dart';

class WhatsAppShare {
  WhatsAppShare._();

  static String money(dynamic value) {
    final n=value is num ? value.toDouble() : double.tryParse('$value')??0;
    return n.toStringAsFixed(2);
  }

  static String _phoneDigits(String? phone) {
    if(phone==null) return '';
    return phone.replaceAll(RegExp(r'[^0-9]'),'');
  }

  static Future<void> send(String text,{String? phone}) async {
    final digits=_phoneDigits(phone);
    final uri=Uri.https('wa.me',digits,{'text':text});
    final ok=await launchUrl(uri,mode:LaunchMode.externalApplication);
    if(!ok) {
      throw StateError(tr('WhatsApp could not be opened on this device.'));
    }
  }

  static Future<void> shareSalesmanCredit(Map<String,Object?> salesman) async {
    final Database db=await AppDatabase.instance.database;
    final id='${salesman['id']}';
    final sales=await db.rawQuery(
      'SELECT invoice_no,total,paid,due,created_at FROM sales WHERE salesman_id=? ORDER BY created_at DESC LIMIT 20',
      [id],
    );
    final totals=await db.rawQuery(
      'SELECT COALESCE(SUM(total),0) total,COALESCE(SUM(paid),0) paid,COALESCE(SUM(due),0) due FROM sales WHERE salesman_id=?',
      [id],
    );
    final loanRows=await db.rawQuery(
      "SELECT COALESCE(SUM(CASE WHEN type='payment' THEN -amount ELSE amount END),0) balance "
      "FROM salesman_loans WHERE salesman_id=? "
      "AND COALESCE(source,'manual') NOT IN ('sale_due','sale_recovery')",
      [id],
    );
    final recentLoans=await db.query(
      'salesman_loans',
      where:'salesman_id=?',
      whereArgs:[id],
      orderBy:'created_at DESC',
      limit:20,
    );
    final t=totals.first;
    final invoiceDue=(t['due'] as num?)?.toDouble()??0;
    final manualLoan=(loanRows.first['balance'] as num?)?.toDouble()??0;
    final outstanding=invoiceDue+manualLoan;
    final b=StringBuffer()
      ..writeln(tr('QAMVIO POS — Salesman Credit Statement'))
      ..writeln('${tr('Salesman')}: ${salesman['name']??''}')
      ..writeln('${tr('Phone')}: ${salesman['phone']??''}')
      ..writeln('${tr('Total sales')}: ${money(t['total'])}')
      ..writeln('${tr('Invoice received')}: ${money(t['paid'])}')
      ..writeln('${tr('Invoice due')}: ${money(invoiceDue)}')
      ..writeln('${tr('Manual loan balance')}: ${money(manualLoan)}')
      ..writeln('${tr('Total outstanding')}: ${money(outstanding)}')
      ..writeln();

    if(recentLoans.isNotEmpty) {
      b.writeln(tr('Recent loan/payment entries:'));
      for(final row in recentLoans) {
        final payment=row['type']=='payment';
        b.writeln(
          '• ${row['created_at']} | ${tr(payment?'Payment received':'Loan Given')} '
          '${money(row['amount'])} | ${row['note']??''}',
        );
      }
      b.writeln();
    }

    if(sales.isEmpty) {
      b.writeln(tr('No assigned invoices found.'));
    } else {
      b.writeln(tr('Recent invoices:'));
      for(final row in sales) {
        b.writeln(
          '• ${row['invoice_no']} | ${row['created_at']} | '
          '${tr('Total')} ${money(row['total'])} | ${tr('Paid')} ${money(row['paid'])} | ${tr('Due')} ${money(row['due'])}',
        );
      }
    }
    b.writeln();
    b.writeln(tr('Generated by QAMVIO POS'));
    await send(b.toString(),phone:salesman['phone']?.toString());
  }

  static Future<void> shareSupplierCredit(Map<String,Object?> supplier) async {
    final Database db=await AppDatabase.instance.database;
    final id='${supplier['id']}';
    final purchases=await db.rawQuery(
      'SELECT total,paid,due,created_at FROM purchases WHERE supplier_id=? ORDER BY created_at DESC LIMIT 20',
      [id],
    );
    final totals=await db.rawQuery(
      'SELECT COALESCE(SUM(total),0) total,COALESCE(SUM(paid),0) paid,COALESCE(SUM(due),0) due FROM purchases WHERE supplier_id=?',
      [id],
    );
    final transactions=await db.query(
      'supplier_transactions',
      where:'supplier_id=?',
      whereArgs:[id],
      orderBy:'created_at DESC',
      limit:20,
    );
    final t=totals.first;
    final b=StringBuffer()
      ..writeln(tr('QAMVIO POS — Supplier Credit Statement'))
      ..writeln('${tr('Supplier')}: ${supplier['name']??''}')
      ..writeln('${tr('Phone')}: ${supplier['phone']??''}')
      ..writeln('${tr('Current payable balance')}: ${money(supplier['balance'])}')
      ..writeln('${tr('Purchases')}: ${money(t['total'])}')
      ..writeln('${tr('Paid on purchases')}: ${money(t['paid'])}')
      ..writeln('${tr('Original purchase due')}: ${money(t['due'])}')
      ..writeln();

    if(transactions.isNotEmpty) {
      b.writeln(tr('Recent supplier payments/receipts:'));
      for(final row in transactions) {
        final paid=row['type']=='payment';
        b.writeln(
          '• ${row['created_at']} | ${tr(paid?'Paid to supplier':'Received from supplier')} '
          '${money(row['amount'])} | ${row['note']??''}',
        );
      }
      b.writeln();
    }

    if(purchases.isEmpty) {
      b.writeln(tr('No purchase records found.'));
    } else {
      b.writeln(tr('Recent purchases:'));
      for(final row in purchases) {
        b.writeln(
          '• ${row['created_at']} | Total ${money(row['total'])} | '
          'Paid ${money(row['paid'])} | Due ${money(row['due'])}',
        );
      }
    }
    b.writeln();
    b.writeln('Generated by QAMVIO POS');
    await send(b.toString(),phone:supplier['phone']?.toString());
  }

  static Future<void> shareInvoice(Map<String,Object?> sale) async {
    final Database db=await AppDatabase.instance.database;
    final id='${sale['id']}';
    final items=await db.query(
      'sale_items',
      where:'sale_id=?',
      whereArgs:[id],
      orderBy:'id',
    );

    Map<String,Object?>? customer;
    final customerId=sale['customer_id']?.toString();
    if(customerId!=null && customerId.isNotEmpty) {
      final rows=await db.query(
        'customers',
        where:'id=?',
        whereArgs:[customerId],
        limit:1,
      );
      if(rows.isNotEmpty) customer=rows.first;
    }

    final b=StringBuffer()
      ..writeln(tr('QAMVIO POS — Sales Invoice'))
      ..writeln('${tr('Invoice')}: ${sale['invoice_no']??''}')
      ..writeln('${tr('Date')}: ${sale['created_at']??''}');

    if(customer!=null) {
      b.writeln('${tr('Customer')}: ${customer['name']??''}');
      if('${customer['phone']??''}'.trim().isNotEmpty) {
        b.writeln('${tr('Phone')}: ${customer['phone']}');
      }
    }

    b.writeln();
    b.writeln(tr('Items:'));
    for(final item in items) {
      b.writeln(
        '• ${item['product_name']} × ${money(item['qty'])} @ '
        '${money(item['price'])} = ${money(item['total'])}',
      );
    }

    b
      ..writeln()
      ..writeln('${tr('Subtotal')}: ${money(sale['subtotal'])}')
      ..writeln('${tr('Discount')}: ${money(sale['discount'])}')
      ..writeln('${tr('Total')}: ${money(sale['total'])}')
      ..writeln('${tr('Paid')}: ${money(sale['paid'])}')
      ..writeln('${tr('Due')}: ${money(sale['due'])}')
      ..writeln()
      ..writeln(tr('Thank you — QAMVIO POS'));

    await send(b.toString(),phone:customer?['phone']?.toString());
  }

  static Future<void> shareBusinessReport() async {
    final Database db=await AppDatabase.instance.database;
    final x=await AppDatabase.instance.extendedReportTotals();
    final dashboard=await AppDatabase.instance.dashboardTotals();

    Future<double> scalar(String sql) async {
      final rows=await db.rawQuery(sql);
      return (rows.first.values.first as num?)?.toDouble()??0;
    }

    final customerBalance=await scalar(
      'SELECT COALESCE(SUM(balance),0) FROM customers',
    );
    final supplierBalance=await scalar(
      'SELECT COALESCE(SUM(balance),0) FROM suppliers',
    );
    final salesmanInvoiceDue=await scalar(
      'SELECT COALESCE(SUM(due),0) FROM sales WHERE salesman_id IS NOT NULL',
    );
    final salesmanManualLoan=await scalar(
      "SELECT COALESCE(SUM(CASE WHEN type='payment' THEN -amount ELSE amount END),0) "
      "FROM salesman_loans "
      "WHERE COALESCE(source,'manual') NOT IN ('sale_due','sale_recovery')",
    );
    final salesmanOutstanding=salesmanInvoiceDue+salesmanManualLoan;

    final b=StringBuffer()
      ..writeln(tr('QAMVIO POS — Full Business Report'))
      ..writeln('${tr('Generated')}: ${DateTime.now().toLocal()}')
      ..writeln()
      ..writeln('${tr('Sales')}: ${money(x['sales'])}')
      ..writeln('${tr('Purchases')}: ${money(x['purchases'])}')
      ..writeln('${tr('Expenses')}: ${money(x['expenses'])}')
      ..writeln('${tr('Profit estimate')}: ${money(x['profit'])}')
      ..writeln()
      ..writeln('${tr('Customer receivables')}: ${money(customerBalance)}')
      ..writeln('${tr('Sales invoice due')}: ${money(x['due'])}')
      ..writeln('${tr('Salesman invoice due')}: ${money(salesmanInvoiceDue)}')
      ..writeln('${tr('Salesman manual loans')}: ${money(salesmanManualLoan)}')
      ..writeln('${tr('Salesman total outstanding')}: ${money(salesmanOutstanding)}')
      ..writeln('${tr('Supplier payable balance')}: ${money(supplierBalance)}')
      ..writeln('${tr('Supplier purchase due')}: ${money(x['supplierDue'])}')
      ..writeln()
      ..writeln('${tr('Inventory cost value')}: ${money(x['stockCost'])}')
      ..writeln('${tr('Inventory sale value')}: ${money(x['stockRetail'])}')
      ..writeln('${tr('Products')}: ${dashboard['products']??0}')
      ..writeln('${tr('Customers')}: ${dashboard['customers']??0}')
      ..writeln()
      ..writeln('Generated by QAMVIO POS');

    await send(b.toString());
  }
}
