-- QAMVIO POS cloud backup history / rollback protection.
-- Supabase keeps the current encrypted backup in qamvio_cloud_backups.
-- This table automatically archives the previous encrypted version before updates.

create table if not exists public.qamvio_cloud_backup_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  payload jsonb not null,
  archived_at timestamptz not null default now()
);

alter table public.qamvio_cloud_backup_history enable row level security;

drop policy if exists "qamvio_history_select_own" on public.qamvio_cloud_backup_history;
create policy "qamvio_history_select_own"
on public.qamvio_cloud_backup_history
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "qamvio_history_delete_own" on public.qamvio_cloud_backup_history;
create policy "qamvio_history_delete_own"
on public.qamvio_cloud_backup_history
for delete
to authenticated
using ((select auth.uid()) = user_id);

revoke all on table public.qamvio_cloud_backup_history from anon;
grant select, delete on table public.qamvio_cloud_backup_history to authenticated;

create or replace function public.qamvio_archive_previous_backup()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.payload is distinct from new.payload then
    insert into public.qamvio_cloud_backup_history(user_id, payload, archived_at)
    values (old.user_id, old.payload, coalesce(old.updated_at, now()));

    delete from public.qamvio_cloud_backup_history h
    where h.user_id = old.user_id
      and h.id not in (
        select id
        from public.qamvio_cloud_backup_history
        where user_id = old.user_id
        order by archived_at desc, id desc
        limit 20
      );
  end if;
  return new;
end;
$$;

drop trigger if exists qamvio_archive_previous_backup_trg on public.qamvio_cloud_backups;
create trigger qamvio_archive_previous_backup_trg
before update on public.qamvio_cloud_backups
for each row
execute function public.qamvio_archive_previous_backup();
