import 'app_strings.dart';

final Map<AppLanguage, Map<String, String>> wordMap = {
  AppLanguage.pashto: const {
    'Date':'نېټه','Stock':'سټاک','Reorder':'بیا فرمایش','Balance':'بیلانس','Total':'ټول',
    'Due':'پور','Customer':'پېرودونکی','Supplier':'عرضه کوونکی','Salesman':'خرڅوونکی',
    'Invoice':'انوایس','Opening':'پیل','Current':'اوسنی','Paid':'ورکړل شوي',
    'Received':'ترلاسه شوي','Amount':'اندازه','Note':'یادښت','From':'له','To':'تر',
    'Type':'ډول','Reference':'حواله','Cash':'نغدي','Phone':'تلیفون','Status':'حالت',
    'Product':'توکی','Qty':'مقدار','Cost':'لګښت','Price':'بیه','Discount':'تخفیف',
    'Recovery':'وصول',
  },
  AppLanguage.dari: const {
    'Date':'تاریخ','Stock':'موجودی','Reorder':'سفارش مجدد','Balance':'موجودی','Total':'مجموع',
    'Due':'باقی','Customer':'مشتری','Supplier':'تأمین‌کننده','Salesman':'فروشنده',
    'Invoice':'فاکتور','Opening':'آغازین','Current':'فعلی','Paid':'پرداخت‌شده',
    'Received':'دریافت‌شده','Amount':'مبلغ','Note':'یادداشت','From':'از','To':'تا',
    'Type':'نوع','Reference':'مرجع','Cash':'نقد','Phone':'تلفن','Status':'وضعیت',
    'Product':'محصول','Qty':'تعداد','Cost':'هزینه','Price':'قیمت','Discount':'تخفیف',
    'Recovery':'دریافت',
  },
  AppLanguage.urdu: const {
    'Date':'تاریخ','Stock':'اسٹاک','Reorder':'ری آرڈر','Balance':'بیلنس','Total':'کل',
    'Due':'بقایا','Customer':'گاہک','Supplier':'سپلائر','Salesman':'سیلز مین',
    'Invoice':'انوائس','Opening':'اوپننگ','Current':'موجودہ','Paid':'ادا شدہ',
    'Received':'وصول شدہ','Amount':'رقم','Note':'نوٹ','From':'سے','To':'تک',
    'Type':'قسم','Reference':'حوالہ','Cash':'کیش','Phone':'فون','Status':'حالت',
    'Product':'مصنوع','Qty':'مقدار','Cost':'لاگت','Price':'قیمت','Discount':'ڈسکاؤنٹ',
    'Recovery':'ریکوری',
  },
  AppLanguage.arabic: const {
    'Date':'التاريخ','Stock':'المخزون','Reorder':'إعادة الطلب','Balance':'الرصيد','Total':'الإجمالي',
    'Due':'المستحق','Customer':'العميل','Supplier':'المورد','Salesman':'مندوب المبيعات',
    'Invoice':'الفاتورة','Opening':'الافتتاحي','Current':'الحالي','Paid':'مدفوع',
    'Received':'مستلم','Amount':'المبلغ','Note':'ملاحظة','From':'من','To':'إلى',
    'Type':'النوع','Reference':'المرجع','Cash':'نقد','Phone':'الهاتف','Status':'الحالة',
    'Product':'المنتج','Qty':'الكمية','Cost':'التكلفة','Price':'السعر','Discount':'الخصم',
    'Recovery':'التحصيل',
  },
  AppLanguage.hindi: const {
    'Date':'तारीख','Stock':'स्टॉक','Reorder':'पुनः ऑर्डर','Balance':'शेष','Total':'कुल',
    'Due':'बकाया','Customer':'ग्राहक','Supplier':'आपूर्तिकर्ता','Salesman':'सेल्समैन',
    'Invoice':'चालान','Opening':'प्रारंभिक','Current':'वर्तमान','Paid':'भुगतान',
    'Received':'प्राप्त','Amount':'राशि','Note':'नोट','From':'से','To':'तक',
    'Type':'प्रकार','Reference':'संदर्भ','Cash':'नकद','Phone':'फोन','Status':'स्थिति',
    'Product':'उत्पाद','Qty':'मात्रा','Cost':'लागत','Price':'मूल्य','Discount':'छूट',
    'Recovery':'वसूली',
  },
  AppLanguage.spanish: const {
    'Date':'Fecha','Stock':'Stock','Reorder':'Reposición','Balance':'Saldo','Total':'Total',
    'Due':'Pendiente','Customer':'Cliente','Supplier':'Proveedor','Salesman':'Vendedor',
    'Invoice':'Factura','Opening':'Inicial','Current':'Actual','Paid':'Pagado',
    'Received':'Recibido','Amount':'Importe','Note':'Nota','From':'Desde','To':'Hasta',
    'Type':'Tipo','Reference':'Referencia','Cash':'Caja','Phone':'Teléfono','Status':'Estado',
    'Product':'Producto','Qty':'Cant.','Cost':'Costo','Price':'Precio','Discount':'Descuento',
    'Recovery':'Recuperación',
  },
  AppLanguage.french: const {
    'Date':'Date','Stock':'Stock','Reorder':'Réapprovisionnement','Balance':'Solde','Total':'Total',
    'Due':'Dû','Customer':'Client','Supplier':'Fournisseur','Salesman':'Vendeur',
    'Invoice':'Facture','Opening':'Initial','Current':'Actuel','Paid':'Payé',
    'Received':'Reçu','Amount':'Montant','Note':'Note','From':'De','To':'À',
    'Type':'Type','Reference':'Référence','Cash':'Caisse','Phone':'Téléphone','Status':'Statut',
    'Product':'Produit','Qty':'Qté','Cost':'Coût','Price':'Prix','Discount':'Remise',
    'Recovery':'Recouvrement',
  },
  AppLanguage.turkish: const {
    'Date':'Tarih','Stock':'Stok','Reorder':'Yeniden Sipariş','Balance':'Bakiye','Total':'Toplam',
    'Due':'Borç','Customer':'Müşteri','Supplier':'Tedarikçi','Salesman':'Satış Elemanı',
    'Invoice':'Fatura','Opening':'Açılış','Current':'Güncel','Paid':'Ödendi',
    'Received':'Alındı','Amount':'Tutar','Note':'Not','From':'Başlangıç','To':'Bitiş',
    'Type':'Tür','Reference':'Referans','Cash':'Nakit','Phone':'Telefon','Status':'Durum',
    'Product':'Ürün','Qty':'Miktar','Cost':'Maliyet','Price':'Fiyat','Discount':'İndirim',
    'Recovery':'Tahsilat',
  },
};
