const Map<String, List<String>> ui1 = {
// [English, Pashto, Dari, Urdu, Arabic, Hindi, Spanish, French, Turkish]
  'Dashboard': ['Dashboard','ډشبورډ','داشبورد','ڈیش بورڈ','لوحة التحكم','डैशबोर्ड','Panel','Tableau de bord','Kontrol Paneli'],
  'Sales': ['Sales','خرڅلاو','فروشات','فروخت','المبيعات','बिक्री','Ventas','Ventes','Satış'],
  'Sales / Cash Report': ['Sales / Cash Report','خرڅلاو / نغدي راپور','فروشات / گزارش نقدی','فروخت / کیش رپورٹ','تقرير المبيعات / النقد','बिक्री / नकद रिपोर्ट','Ventas / Informe de caja','Ventes / Rapport de caisse','Satış / Nakit Raporu'],
  'Fuel / Oil Pump': ['Fuel / Oil Pump','د تېلو پمپ','پمپ سوخت / روغن','فیول / آئل پمپ','مضخة الوقود / الزيت','ईंधन / तेल पंप','Bomba de combustible / aceite','Pompe carburant / huile','Yakıt / Yağ Pompası'],
  'Pharmacy': ['Pharmacy','درملتون','داروخانه','فارمیسی','الصيدلية','फार्मेसी','Farmacia','Pharmacie','Eczane'],
  'Stock': ['Stock','سټاک','موجودی','اسٹاک','المخزون','स्टॉक','Stock','Stock','Stok'],
  'Stock Ledger': ['Stock Ledger','د سټاک لیجر','دفتر موجودی','اسٹاک لیجر','دفتر المخزون','स्टॉक लेजर','Libro de stock','Grand livre de stock','Stok Defteri'],
  'Products': ['Products','توکي','محصولات','مصنوعات','المنتجات','उत्पाद','Productos','Produits','Ürünler'],
  'Purchases': ['Purchases','پېرودونه','خریدها','خریداری','المشتريات','खरीदारी','Compras','Achats','Satın Almalar'],
  'Customers': ['Customers','پېرودونکي','مشتریان','گاہک','العملاء','ग्राहक','Clientes','Clients','Müşteriler'],
  'Suppliers': ['Suppliers','عرضه کوونکي','تأمین‌کنندگان','سپلائرز','الموردون','आपूर्तिकर्ता','Proveedores','Fournisseurs','Tedarikçiler'],
  'Salesmen': ['Salesmen','خرڅوونکي','فروشندگان','سیلز مین','مندوبو المبيعات','सेल्समैन','Vendedores','Vendeurs','Satış Elemanları'],
  'Expenses': ['Expenses','لګښتونه','مصارف','اخراجات','المصروفات','खर्चे','Gastos','Dépenses','Giderler'],
  'Reports': ['Reports','راپورونه','گزارش‌ها','رپورٹس','التقارير','रिपोर्ट','Informes','Rapports','Raporlar'],
  'Cash Book': ['Cash Book','نغدي کتاب','دفتر نقدی','کیش بک','دفتر النقدية','कैश बुक','Libro de caja','Livre de caisse','Kasa Defteri'],
  'Daily Closing': ['Daily Closing','ورځنی تړل','بستن روزانه','ڈیلی کلوزنگ','الإغلاق اليومي','दैनिक समापन','Cierre diario','Clôture quotidienne','Günlük Kapanış'],
  'Customer Loans': ['Customer Loans','د پېرودونکو پورونه','قرض مشتریان','کسٹمر لونز','ديون العملاء','ग्राहक ऋण','Préstamos de clientes','Prêts clients','Müşteri Borçları'],
  'Salesman Loans': ['Salesman Loans','د خرڅوونکو پورونه','قرض فروشندگان','سیلز مین لونز','ديون مندوبي المبيعات','सेल्समैन ऋण','Préstamos de vendedores','Prêts vendeurs','Satış Elemanı Borçları'],
  'Customer Statement / Ledger': ['Customer Statement / Ledger','د پېرودونکي حساب / لیجر','صورت حساب / دفتر مشتری','کسٹمر اسٹیٹمنٹ / لیجر','كشف حساب العميل','ग्राहक स्टेटमेंट / लेजर','Estado / Libro del cliente','Relevé / Grand livre client','Müşteri Ekstresi / Defter'],
  'Supplier Statement / Ledger': ['Supplier Statement / Ledger','د عرضه کوونکي حساب / لیجر','صورت حساب / دفتر تأمین‌کننده','سپلائر اسٹیٹمنٹ / لیجر','كشف حساب المورد','आपूर्तिकर्ता स्टेटमेंट / लेजर','Estado / Libro del proveedor','Relevé / Grand livre fournisseur','Tedarikçi Ekstresi / Defter'],
  'Salesman Statement / Ledger': ['Salesman Statement / Ledger','د خرڅوونکي حساب / لیجر','صورت حساب / دفتر فروشنده','سیلز مین اسٹیٹمنٹ / لیجر','كشف حساب مندوب المبيعات','सेल्समैन स्टेटमेंट / लेजर','Estado / Libro del vendedor','Relevé / Grand livre vendeur','Satış Elemanı Ekstresi / Defter'],
  'Owner / Partner Money': ['Owner / Partner Money','د مالک / شریک پیسې','پول مالک / شریک','مالک / پارٹنر رقم','أموال المالك / الشريك','मालिक / भागीदार धन','Dinero del propietario / socio','Argent propriétaire / associé','Sahip / Ortak Parası'],
  'Backup / Restore': ['Backup / Restore','بیک اپ / بېرته راګرځول','پشتیبان / بازیابی','بیک اپ / ریسٹور','نسخ احتياطي / استعادة','बैकअप / पुनर्स्थापना','Copia / Restaurar','Sauvegarde / Restaurer','Yedekle / Geri Yükle'],
  'Users / Login': ['Users / Login','کاروونکي / ننوتل','کاربران / ورود','یوزرز / لاگ اِن','المستخدمون / تسجيل الدخول','उपयोगकर्ता / लॉगिन','Usuarios / Inicio de sesión','Utilisateurs / Connexion','Kullanıcılar / Giriş'],
  'Safety Center': ['Safety Center','امنیت مرکز','مرکز امنیت','سیفٹی سینٹر','مركز الأمان','सुरक्षा केंद्र','Centro de seguridad','Centre de sécurité','Güvenlik Merkezi'],
  'Recycle Bin': ['Recycle Bin','کثافت دان','سطل بازیافت','ری سائیکل بن','سلة المحذوفات','रीसायकल बिन','Papelera','Corbeille','Geri Dönüşüm Kutusu'],
  'Delete Entry': ['Delete Entry','ریکارډ ړنګول','حذف رکورد','انٹری حذف کریں','حذف السجل','एंट्री हटाएँ','Eliminar entrada','Supprimer l’entrée','Kaydı Sil'],
  'Quick Search': ['Quick Search','چټک لټون','جستجوی سریع','فوری تلاش','بحث سريع','त्वरित खोज','Búsqueda rápida','Recherche rapide','Hızlı Arama'],
  'Discount Report': ['Discount Report','د تخفیف راپور','گزارش تخفیف','ڈسکاؤنٹ رپورٹ','تقرير الخصومات','छूट रिपोर्ट','Informe de descuentos','Rapport des remises','İndirim Raporu'],
  'Language': ['Language','ژبه','زبان','زبان','اللغة','भाषा','Idioma','Langue','Dil'],
  'Save': ['Save','خوندي کول','ذخیره','محفوظ کریں','حفظ','सहेजें','Guardar','Enregistrer','Kaydet'],
  'Cancel': ['Cancel','لغوه','لغو','منسوخ','إلغاء','रद्द करें','Cancelar','Annuler','İptal'],
  'Delete': ['Delete','ړنګول','حذف','حذف کریں','حذف','हटाएँ','Eliminar','Supprimer','Sil'],
  'Edit': ['Edit','سمون','ویرایش','ترمیم','تعديل','संपादित करें','Editar','Modifier','Düzenle'],
  'Continue': ['Continue','دوام','ادامه','جاری رکھیں','متابعة','जारी रखें','Continuar','Continuer','Devam'],
  'Close': ['Close','تړل','بستن','بند کریں','إغلاق','बंद करें','Cerrar','Fermer','Kapat'],
  'Search': ['Search','لټون','جستجو','تلاش','بحث','खोज','Buscar','Rechercher','Ara'],
  'Print': ['Print','چاپ','چاپ','پرنٹ','طباعة','प्रिंट','Imprimir','Imprimer','Yazdır'],
  'Restore': ['Restore','بېرته راګرځول','بازیابی','ریسٹور','استعادة','पुनर्स्थापित करें','Restaurar','Restaurer','Geri Yükle'],
  'Refresh': ['Refresh','تازه کول','تازه‌سازی','ریفریش','تحديث','रीफ्रेश','Actualizar','Actualiser','Yenile'],
  'WhatsApp': ['WhatsApp','واټس‌اپ','واتساپ','واٹس ایپ','واتساب','व्हाट्सऐप','WhatsApp','WhatsApp','WhatsApp'],
  'Copy': ['Copy','کاپي','کپی','کاپی','نسخ','कॉपी','Copiar','Copier','Kopyala'],
  'Not now': ['Not now','اوس نه','فعلاً نه','ابھی نہیں','ليس الآن','अभी नहीं','Ahora no','Pas maintenant','Şimdi değil'],
  'Back to sign in': ['Back to sign in','بېرته ننوتلو ته','بازگشت به ورود','واپس لاگ اِن','العودة لتسجيل الدخول','लॉगिन पर वापस','Volver al inicio','Retour à la connexion','Girişe Dön'],
  'Sign out': ['Sign out','وتل','خروج','سائن آؤٹ','تسجيل الخروج','साइन आउट','Cerrar sesión','Se déconnecter','Çıkış Yap'],
  'Logout': ['Logout','وتل','خروج','لاگ آؤٹ','تسجيل الخروج','लॉग आउट','Cerrar sesión','Déconnexion','Çıkış'],
  'Add': ['Add','زیاتول','افزودن','شامل کریں','إضافة','जोड़ें','Añadir','Ajouter','Ekle'],
  'Add Line': ['Add Line','کرښه زیاتول','افزودن ردیف','لائن شامل کریں','إضافة سطر','पंक्ति जोड़ें','Añadir línea','Ajouter une ligne','Satır Ekle'],
  'Add Entry': ['Add Entry','ریکارډ زیاتول','افزودن رکورد','انٹری شامل کریں','إضافة سجل','एंट्री जोड़ें','Añadir entrada','Ajouter une entrée','Kayıt Ekle'],
  'Create user': ['Create user','کاروونکی جوړول','ایجاد کاربر','یوزر بنائیں','إنشاء مستخدم','उपयोगकर्ता बनाएँ','Crear usuario','Créer un utilisateur','Kullanıcı Oluştur'],
  'Date': ['Date','نېټه','تاریخ','تاریخ','التاريخ','तारीख','Fecha','Date','Tarih'],
  'Invoice': ['Invoice','انوایس','فاکتور','انوائس','فاتورة','चालान','Factura','Facture','Fatura'],
};
