const Map<String, List<String>> ui6 = {
  'Actual Cash': ['Actual Cash','اصلي نغدي','نقد واقعی','اصل کیش','النقد الفعلي','वास्तविक नकद','Efectivo real','Espèces réelles','Gerçek Nakit'],
  'Add Payment / Receipt': ['Add Payment / Receipt','تادیه / رسید زیاتول','افزودن پرداخت / دریافت','ادائیگی / رسید شامل کریں','إضافة دفعة / إيصال','भुगतान / प्राप्ति जोड़ें','Añadir pago / recibo','Ajouter paiement / reçu','Ödeme / Tahsilat Ekle'],
  'Business Daily Closing': ['Business Daily Closing','د کاروبار ورځنی تړل','بستن روزانه کسب‌وکار','کاروباری ڈیلی کلوزنگ','الإغلاق اليومي للنشاط','व्यवसाय दैनिक समापन','Cierre diario del negocio','Clôture quotidienne de l’entreprise','İşletme Günlük Kapanışı'],
  'Cancel Edit': ['Cancel Edit','سمون لغوه','لغو ویرایش','ترمیم منسوخ','إلغاء التعديل','संपादन रद्द करें','Cancelar edición','Annuler la modification','Düzenlemeyi İptal Et'],
  'Capacity': ['Capacity','ظرفیت','ظرفیت','گنجائش','السعة','क्षमता','Capacidad','Capacité','Kapasite'],
  'Capacity (L)': ['Capacity (L)','ظرفیت (L)','ظرفیت (L)','گنجائش (L)','السعة (L)','क्षमता (L)','Capacidad (L)','Capacité (L)','Kapasite (L)'],
  'Cash': ['Cash','نغدي','نقد','کیش','نقد','नकद','Efectivo','Espèces','Nakit'],
  'Cash = Total': ['Cash = Total','نغدي = ټول','نقد = مجموع','کیش = کل','النقد = الإجمالي','नकद = कुल','Efectivo = Total','Espèces = Total','Nakit = Toplam'],
  'Cash Received': ['Cash Received','ترلاسه شوې نغدي','نقد دریافت‌شده','وصول شدہ کیش','النقد المستلم','प्राप्त नकद','Efectivo recibido','Espèces reçues','Alınan Nakit'],
  'Closing': ['Closing','تړل','بستن','کلوزنگ','الإغلاق','समापन','Cierre','Clôture','Kapanış'],
  'Closing Meter': ['Closing Meter','د پای میټر','متر پایانی','کلوزنگ میٹر','عداد الإغلاق','क्लोजिंग मीटर','Medidor final','Compteur final','Kapanış Sayacı'],
  'Cost / Liter': ['Cost / Liter','لګښت / لیتر','هزینه / لیتر','لاگت / لیٹر','التكلفة / لتر','लागत / लीटर','Costo / Litro','Coût / Litre','Maliyet / Litre'],
  'Cost/L': ['Cost/L','لګښت/L','هزینه/L','لاگت/L','التكلفة/L','लागत/L','Costo/L','Coût/L','Maliyet/L'],
  'Current Liters': ['Current Liters','اوسني لیترونه','لیتر فعلی','موجودہ لیٹر','اللترات الحالية','वर्तमान लीटर','Litros actuales','Litres actuels','Mevcut Litre'],
  'Customer Loan / Payment': ['Customer Loan / Payment','د پېرودونکي پور / تادیه','قرض / پرداخت مشتری','کسٹمر لون / ادائیگی','قرض / دفع العميل','ग्राहक ऋण / भुगतान','Préstamo / pago del cliente','Prêt / paiement client','Müşteri Borç / Ödeme'],
  'Customer Name': ['Customer Name','د پېرودونکي نوم','نام مشتری','کسٹمر نام','اسم العميل','ग्राहक नाम','Nombre del cliente','Nom du client','Müşteri Adı'],
  'Expense Category': ['Expense Category','د لګښت کټګوري','دسته هزینه','اخراجات کیٹیگری','فئة المصروف','खर्च श्रेणी','Categoría de gasto','Catégorie de dépense','Gider Kategorisi'],
  'Expense Name': ['Expense Name','د لګښت نوم','نام هزینه','اخراجات نام','اسم المصروف','खर्च का नाम','Nombre del gasto','Nom de la dépense','Gider Adı'],
  'Extra Expense': ['Extra Expense','اضافي لګښت','هزینه اضافی','اضافی اخراجات','مصروف إضافي','अतिरिक्त खर्च','Gasto extra','Dépense supplémentaire','Ek Gider'],
  'Free Capacity': ['Free Capacity','خالي ظرفیت','ظرفیت خالی','خالی گنجائش','السعة المتاحة','खाली क्षमता','Capacidad libre','Capacité libre','Boş Kapasite'],
  'Fuel Daily Closing': ['Fuel Daily Closing','د تېلو ورځنی تړل','بستن روزانه سوخت','فیول ڈیلی کلوزنگ','الإغلاق اليومي للوقود','ईंधन दैनिक समापन','Cierre diario de combustible','Clôture quotidienne carburant','Yakıt Günlük Kapanışı'],
  'Fuel Product': ['Fuel Product','د تېلو توکی','محصول سوخت','فیول پروڈکٹ','منتج الوقود','ईंधन उत्पाद','Producto de combustible','Produit carburant','Yakıt Ürünü'],
  'Fuel Purchase / Tank Delivery': ['Fuel Purchase / Tank Delivery','د تېلو پېرود / ټانک سپارنه','خرید سوخت / تحویل مخزن','فیول خرید / ٹینک ڈیلیوری','شراء الوقود / تعبئة الخزان','ईंधन खरीद / टैंक डिलीवरी','Compra de combustible / entrega a tanque','Achat carburant / livraison cuve','Yakıt Alımı / Tank Teslimatı'],
  'Fuel Tanks': ['Fuel Tanks','د تېلو ټانکونه','مخازن سوخت','فیول ٹینکس','خزانات الوقود','ईंधन टैंक','Tanques de combustible','Cuves de carburant','Yakıt Tankları'],
  'Last Meter': ['Last Meter','وروستی میټر','آخرین متر','آخری میٹر','آخر عداد','अंतिम मीटर','Último medidor','Dernier compteur','Son Sayaç'],
  'Liters': ['Liters','لیترونه','لیتر','لیٹر','لترات','लीटर','Litros','Litres','Litre'],
  'Loans & Credit': ['Loans & Credit','پورونه او کریډیټ','قرض و اعتبار','لونز اور کریڈٹ','القروض والائتمان','ऋण और क्रेडिट','Préstamos y crédito','Prêts et crédit','Borçlar ve Kredi'],
  'Lock / Logout': ['Lock / Logout','قلف / وتل','قفل / خروج','لاک / لاگ آؤٹ','قفل / تسجيل الخروج','लॉक / लॉग आउट','Bloquear / salir','Verrouiller / se déconnecter','Kilitle / Çıkış'],
  'Mechanic': ['Mechanic','میخانیک','مکانیک','مکینک','ميكانيكي','मैकेनिक','Mecánico','Mécanicien','Tamirci'],
  'Morning / Evening / Night': ['Morning / Evening / Night','سهار / ماښام / شپه','صبح / عصر / شب','صبح / شام / رات','صباح / مساء / ليل','सुबह / शाम / रात','Mañana / tarde / noche','Matin / soir / nuit','Sabah / Akşam / Gece'],
  'No Salesman': ['No Salesman','خرڅوونکی نشته','فروشنده ندارد','کوئی سیلز مین نہیں','لا يوجد مندوب مبيعات','कोई सेल्समैन नहीं','Sin vendedor','Aucun vendeur','Satış Elemanı Yok'],
  'Nozzle': ['Nozzle','نوزل','نازل','نوزل','الفوهة','नोज़ल','Boquilla','Pistolet','Nozul'],
  'Nozzle / Pump Name': ['Nozzle / Pump Name','د نوزل / پمپ نوم','نام نازل / پمپ','نوزل / پمپ نام','اسم الفوهة / المضخة','नोज़ल / पंप नाम','Nombre boquilla / bomba','Nom pistolet / pompe','Nozul / Pompa Adı'],
  'Nozzle Meter Sale / Shift': ['Nozzle Meter Sale / Shift','د نوزل میټر خرڅلاو / شفټ','فروش متر نازل / شیفت','نوزل میٹر سیل / شفٹ','بيع عداد الفوهة / الوردية','नोज़ल मीटर बिक्री / शिफ्ट','Venta por medidor / turno','Vente compteur / équipe','Nozul Sayaç Satışı / Vardiya'],
  'Opening Cash': ['Opening Cash','پیل نغدي','نقد آغازین','اوپننگ کیش','النقد الافتتاحي','प्रारंभिक नकद','Efectivo inicial','Espèces initiales','Açılış Nakdi'],
  'Opening Liters': ['Opening Liters','پیل لیترونه','لیتر آغازین','اوپننگ لیٹر','اللترات الافتتاحية','प्रारंभिक लीटर','Litros iniciales','Litres initiaux','Açılış Litresi'],
  'Opening Meter': ['Opening Meter','پیل میټر','متر آغازین','اوپننگ میٹر','عداد الافتتاح','प्रारंभिक मीटर','Medidor inicial','Compteur initial','Açılış Sayacı'],
};
