const Map<String, List<String>> ui13 = {
  'Admin': ['Admin','اډمین','ادمین','ایڈمن','مدير','एडमिन','Administrador','Administrateur','Yönetici'],
  'Manager': ['Manager','منیجر','مدیر','منیجر','مدير','प्रबंधक','Gerente','Gestionnaire','Yönetici'],
  'Cashier': ['Cashier','کاشیر','صندوقدار','کیشئر','أمين الصندوق','कैशियर','Cajero','Caissier','Kasiyer'],
  'Viewer': ['Viewer','کتونکی','بیننده','ناظر','مشاهد','दर्शक','Visor','Lecteur','Görüntüleyici'],
  'Retail Store': ['Retail Store','پرچون پلورنځی','فروشگاه پرچون','ریٹیل اسٹور','متجر تجزئة','रिटेल स्टोर','Tienda minorista','Magasin de détail','Perakende Mağaza'],
  'Oil / Fuel': ['Oil / Fuel','تېل / سون توکي','روغن / سوخت','آئل / فیول','زيت / وقود','तेल / ईंधन','Aceite / Combustible','Huile / Carburant','Yağ / Yakıt'],
  'Restaurant': ['Restaurant','رستورانت','رستوران','ریستوران','مطعم','रेस्तरां','Restaurante','Restaurant','Restoran'],
  'BUSINESS': ['BUSINESS','کاروبار','کسب‌وکار','کاروبار','النشاط','व्यवसाय','NEGOCIO','ENTREPRISE','İŞLETME'],
  'SALES': ['SALES','خرڅلاو','فروشات','فروخت','المبيعات','बिक्री','VENTAS','VENTES','SATIŞ'],
  'STOCK': ['STOCK','سټاک','موجودی','اسٹاک','المخزون','स्टॉक','STOCK','STOCK','STOK'],
  'PEOPLE': ['PEOPLE','خلک','افراد','لوگ','الأشخاص','लोग','PERSONAS','PERSONNES','KİŞİLER'],
  'MONEY': ['MONEY','پیسې','پول','رقم','المال','पैसा','DINERO','ARGENT','PARA'],
  'REPORTS': ['REPORTS','راپورونه','گزارش‌ها','رپورٹس','التقارير','रिपोर्ट','INFORMES','RAPPORTS','RAPORLAR'],
  'SYSTEM': ['SYSTEM','سیستم','سیستم','سسٹم','النظام','सिस्टम','SISTEMA','SYSTÈME','SİSTEM'],
  'Account': ['Account','حساب','حساب','اکاؤنٹ','الحساب','खाता','Cuenta','Compte','Hesap'],
  'Balance': ['Balance','بیلانس','موجودی','بیلنس','الرصيد','शेष','Saldo','Solde','Bakiye'],
  'Business': ['Business','کاروبار','کسب‌وکار','کاروبار','النشاط','व्यवसाय','Negocio','Entreprise','İşletme'],
  'Current': ['Current','اوسنی','فعلی','موجودہ','الحالي','वर्तमान','Actual','Actuel','Güncel'],
  'Opening': ['Opening','پیل','آغازین','اوپننگ','افتتاحي','प्रारंभिक','Apertura','Ouverture','Açılış'],
  'Payment': ['Payment','تادیه','پرداخت','ادائیگی','الدفع','भुगतान','Pago','Paiement','Ödeme'],
  'Price': ['Price','بیه','قیمت','قیمت','السعر','मूल्य','Precio','Prix','Fiyat'],
  'Reorder': ['Reorder','بیا فرمایش','سفارش مجدد','ری آرڈر','إعادة الطلب','पुनः ऑर्डर','Reposición','Réapprovisionnement','Yeniden Sipariş'],
  'Section': ['Section','برخه','بخش','سیکشن','القسم','अनुभाग','Sección','Section','Bölüm'],
  'Sold': ['Sold','پلورل شوی','فروخته‌شده','فروخت شدہ','مباع','बेचा गया','Vendido','Vendu','Satılan'],
  'Purchased': ['Purchased','پېرودل شوی','خریداری‌شده','خریدا گیا','مُشترى','खरीदा गया','Comprado','Acheté','Satın Alınan'],
  'Given': ['Given','ورکړل شوی','داده‌شده','دیا گیا','مُعطى','दिया गया','Dado','Donné','Verilen'],
  'Ref': ['Ref','حواله','مرجع','حوالہ','مرجع','संदर्भ','Ref.','Réf.','Ref.'],
  'You': ['You','تاسو','شما','آپ','أنت','आप','Tú','Vous','Siz'],
  'Daily': ['Daily','ورځنی','روزانه','روزانہ','يومي','दैनिक','Diario','Quotidien','Günlük'],
  'Monthly': ['Monthly','میاشتنی','ماهانه','ماہانہ','شهري','मासिक','Mensual','Mensuel','Aylık'],
  'Yearly': ['Yearly','کلنی','سالانه','سالانہ','سنوي','वार्षिक','Anual','Annuel','Yıllık'],
  'Auto if blank': ['Auto if blank','که تش وي، اتومات','اگر خالی باشد، خودکار','خالی ہو تو خودکار','تلقائي إذا كان فارغاً','खाली हो तो स्वचालित','Automático si está vacío','Automatique si vide','Boşsa otomatik'],
  'Add Item': ['Add Item','توکی زیات کړئ','افزودن قلم','آئٹم شامل کریں','إضافة عنصر','आइटम जोड़ें','Añadir artículo','Ajouter un article','Kalem Ekle'],
  'Add Money': ['Add Money','پیسې زیاتې کړئ','افزودن پول','رقم شامل کریں','إضافة مال','धन जोड़ें','Añadir dinero','Ajouter de l’argent','Para Ekle'],
  'Adjust': ['Adjust','سمون','تنظیم','ایڈجسٹ','تعديل','समायोजन','Ajustar','Ajuster','Ayarla'],
  'Current Due': ['Current Due','اوسنی پور','باقی فعلی','موجودہ بقایا','المستحق الحالي','वर्तमान बकाया','Pendiente actual','Dû actuel','Güncel Borç'],
  'G.TOTAL': ['G.TOTAL','ټولیز','مجموع کل','گرینڈ ٹوٹل','الإجمالي العام','कुल योग','TOTAL GENERAL','TOTAL GÉNÉRAL','GENEL TOPLAM'],
  'Net Sale': ['Net Sale','خالص خرڅلاو','فروش خالص','خالص فروخت','صافي البيع','शुद्ध बिक्री','Venta neta','Vente nette','Net Satış'],
  'Net Sales': ['Net Sales','خالص خرڅلاو','فروش خالص','خالص فروخت','صافي المبيعات','शुद्ध बिक्री','Ventas netas','Ventes nettes','Net Satışlar'],
  'Sold Qty': ['Sold Qty','پلورل شوی مقدار','مقدار فروخته‌شده','فروخت شدہ مقدار','الكمية المباعة','बेची मात्रा','Cantidad vendida','Quantité vendue','Satılan Miktar'],
  'T Amount': ['T Amount','ټوله اندازه','مبلغ کل','کل رقم','المبلغ الإجمالي','कुल राशि','Importe total','Montant total','Toplam Tutar'],
  'Total Sale (Qty)': ['Total Sale (Qty)','ټول خرڅلاو (مقدار)','کل فروش (تعداد)','کل فروخت (مقدار)','إجمالي البيع (الكمية)','कुल बिक्री (मात्रा)','Venta total (Cant.)','Vente totale (Qté)','Toplam Satış (Miktar)'],
  'Loan / Give credit': ['Loan / Give credit','پور / کریډیټ ورکول','قرض / اعتبار دادن','لون / کریڈٹ دیں','قرض / منح ائتمان','ऋण / क्रेडिट दें','Préstamo / dar crédito','Prêt / accorder crédit','Borç / Kredi Ver'],
  'Loans / Credit': ['Loans / Credit','پورونه / کریډیټ','قرض / اعتبار','لونز / کریڈٹ','القروض / الائتمان','ऋण / क्रेडिट','Préstamos / crédito','Prêts / crédit','Borçlar / Kredi'],
};
