const Map<String, List<String>> ui2 = {
  'Invoice No': ['Invoice No','د انوایس شمېره','شماره فاکتور','انوائس نمبر','رقم الفاتورة','चालान नंबर','N.º factura','N° facture','Fatura No'],
  'Customer': ['Customer','پېرودونکی','مشتری','گاہک','عميل','ग्राहक','Cliente','Client','Müşteri'],
  'Supplier': ['Supplier','عرضه کوونکی','تأمین‌کننده','سپلائر','مورد','आपूर्तिकर्ता','Proveedor','Fournisseur','Tedarikçi'],
  'Salesman': ['Salesman','خرڅوونکی','فروشنده','سیلز مین','مندوب المبيعات','सेल्समैन','Vendedor','Vendeur','Satış Elemanı'],
  'Product': ['Product','توکی','محصول','مصنوع','المنتج','उत्पाद','Producto','Produit','Ürün'],
  'Qty': ['Qty','مقدار','تعداد','مقدار','الكمية','मात्रा','Cant.','Qté','Miktar'],
  'Cost': ['Cost','لګښت','هزینه','لاگت','التكلفة','लागत','Costo','Coût','Maliyet'],
  'Amount': ['Amount','اندازه','مبلغ','رقم','المبلغ','राशि','Importe','Montant','Tutar'],
  'Total': ['Total','ټول','مجموع','کل','الإجمالي','कुल','Total','Total','Toplam'],
  'Paid': ['Paid','ورکړل شوي','پرداخت‌شده','ادا شدہ','مدفوع','भुगतान','Pagado','Payé','Ödendi'],
  'Received': ['Received','ترلاسه شوي','دریافت‌شده','وصول شدہ','مستلم','प्राप्त','Recibido','Reçu','Alındı'],
  'Due': ['Due','پور','باقی','بقایا','مستحق','बकाया','Pendiente','Dû','Borç'],
  'Recovery': ['Recovery','وصول','دریافت','ریکوری','تحصيل','वसूली','Recuperación','Recouvrement','Tahsilat'],
  'Discount': ['Discount','تخفیف','تخفیف','ڈسکاؤنٹ','خصم','छूट','Descuento','Remise','İndirim'],
  'Note': ['Note','یادښت','یادداشت','نوٹ','ملاحظة','नोट','Nota','Note','Not'],
  'Phone': ['Phone','تلیفون','تلفن','فون','الهاتف','फोन','Teléfono','Téléphone','Telefon'],
  'Address': ['Address','پته','آدرس','پتہ','العنوان','पता','Dirección','Adresse','Adres'],
  'Currency': ['Currency','اسعار','واحد پول','کرنسی','العملة','मुद्रा','Moneda','Devise','Para Birimi'],
  'Business Type': ['Business Type','د کاروبار ډول','نوع کسب‌وکار','کاروبار کی قسم','نوع النشاط','व्यवसाय प्रकार','Tipo de negocio','Type d’entreprise','İşletme Türü'],
  'Role': ['Role','رول','نقش','کردار','الدور','भूमिका','Rol','Rôle','Rol'],
  'Password': ['Password','پاسورډ','رمز عبور','پاس ورڈ','كلمة المرور','पासवर्ड','Contraseña','Mot de passe','Şifre'],
  'Confirm password': ['Confirm password','پاسورډ تایید','تأیید رمز عبور','پاس ورڈ کی تصدیق','تأكيد كلمة المرور','पासवर्ड की पुष्टि','Confirmar contraseña','Confirmer le mot de passe','Şifreyi Doğrula'],
  'Email or mobile': ['Email or mobile','برېښنالیک یا موبایل','ایمیل یا موبایل','ای میل یا موبائل','البريد أو الجوال','ईमेल या मोबाइल','Correo o móvil','E-mail ou mobile','E-posta veya Mobil'],
  'Credit Limit': ['Credit Limit','د پور حد','حد اعتبار','کریڈٹ حد','حد الائتمان','क्रेडिट सीमा','Límite de crédito','Limite de crédit','Kredi Limiti'],
  'Opening Balance': ['Opening Balance','پیل بیلانس','موجودی آغازین','اوپننگ بیلنس','الرصيد الافتتاحي','प्रारंभिक शेष','Saldo inicial','Solde initial','Açılış Bakiyesi'],
  'Current Balance': ['Current Balance','اوسنی بیلانس','موجودی فعلی','موجودہ بیلنس','الرصيد الحالي','वर्तमान शेष','Saldo actual','Solde actuel','Güncel Bakiye'],
  'Current Stock': ['Current Stock','اوسنی سټاک','موجودی فعلی','موجودہ اسٹاک','المخزون الحالي','वर्तमान स्टॉक','Stock actual','Stock actuel','Mevcut Stok'],
  'Opening Qty': ['Opening Qty','پیل مقدار','تعداد آغازین','اوپننگ مقدار','الكمية الافتتاحية','प्रारंभिक मात्रा','Cantidad inicial','Qté initiale','Açılış Miktarı'],
  'Reorder Level': ['Reorder Level','د بیا فرمایش کچه','سطح سفارش مجدد','ری آرڈر لیول','حد إعادة الطلب','पुनः ऑर्डर स्तर','Nivel de reposición','Niveau de réapprovisionnement','Yeniden Sipariş Seviyesi'],
  'Sale Price': ['Sale Price','د خرڅلاو بیه','قیمت فروش','فروخت قیمت','سعر البيع','बिक्री मूल्य','Precio de venta','Prix de vente','Satış Fiyatı'],
  'Cost Price': ['Cost Price','د پېر بیه','قیمت خرید','لاگت قیمت','سعر التكلفة','लागत मूल्य','Precio de costo','Prix de revient','Maliyet Fiyatı'],
  'Stock Value': ['Stock Value','د سټاک ارزښت','ارزش موجودی','اسٹاک ویلیو','قيمة المخزون','स्टॉक मूल्य','Valor del stock','Valeur du stock','Stok Değeri'],
  'Status': ['Status','حالت','وضعیت','حالت','الحالة','स्थिति','Estado','Statut','Durum'],
  'Type': ['Type','ډول','نوع','قسم','النوع','प्रकार','Tipo','Type','Tür'],
  'Reference': ['Reference','حواله','مرجع','حوالہ','المرجع','संदर्भ','Referencia','Référence','Referans'],
  'Cash In': ['Cash In','نغدي داخل','ورودی نقدی','کیش اِن','نقد داخل','नकद आवक','Entrada de caja','Encaissement','Nakit Girişi'],
  'Cash Out': ['Cash Out','نغدي خارج','خروجی نقدی','کیش آؤٹ','نقد خارج','नकद निकासी','Salida de caja','Décaissement','Nakit Çıkışı'],
  'Running Balance': ['Running Balance','روان بیلانس','مانده جاری','رننگ بیلنس','الرصيد الجاري','चलता शेष','Saldo acumulado','Solde courant','Cari Bakiye'],
  'From': ['From','له','از','سے','من','से','Desde','De','Başlangıç'],
  'To': ['To','تر','تا','تک','إلى','तक','Hasta','À','Bitiş'],
  'Month': ['Month','میاشت','ماه','مہینہ','الشهر','महीना','Mes','Mois','Ay'],
  'Year': ['Year','کال','سال','سال','السنة','वर्ष','Año','Année','Yıl'],
  'Report Type': ['Report Type','د راپور ډول','نوع گزارش','رپورٹ کی قسم','نوع التقرير','रिपोर्ट प्रकार','Tipo de informe','Type de rapport','Rapor Türü'],
  'Search Product': ['Search Product','توکی ولټوئ','جستجوی محصول','مصنوع تلاش کریں','بحث عن منتج','उत्पाद खोजें','Buscar producto','Rechercher un produit','Ürün Ara'],
  'Today\'s Summary': ['Today\'s Summary','د نن لنډیز','خلاصه امروز','آج کا خلاصہ','ملخص اليوم','आज का सारांश','Resumen de hoy','Résumé du jour','Bugünün Özeti'],
  'Owner Summary': ['Owner Summary','د مالک لنډیز','خلاصه مالک','مالک خلاصہ','ملخص المالك','मालिक सारांश','Resumen del propietario','Résumé du propriétaire','Sahip Özeti'],
  'Business Totals': ['Business Totals','د کاروبار ټولیز','مجموع کسب‌وکار','کاروباری کل','إجماليات النشاط','व्यवसाय कुल','Totales del negocio','Totaux de l’entreprise','İşletme Toplamları'],
  'This Week vs Last Week': ['This Week vs Last Week','دا اوونۍ د تېرې اوونۍ پر وړاندې','این هفته در برابر هفته قبل','یہ ہفتہ بمقابلہ پچھلا ہفتہ','هذا الأسبوع مقابل الأسبوع الماضي','इस सप्ताह बनाम पिछले सप्ताह','Esta semana vs la pasada','Cette semaine vs la précédente','Bu Hafta / Geçen Hafta'],
  'Visual Analytics': ['Visual Analytics','بصري شننه','تحلیل بصری','بصری تجزیہ','تحليلات مرئية','दृश्य विश्लेषण','Analítica visual','Analyse visuelle','Görsel Analiz'],
  'Today\'s Activity': ['Today\'s Activity','د نن فعالیت','فعالیت امروز','آج کی سرگرمی','نشاط اليوم','आज की गतिविधि','Actividad de hoy','Activité du jour','Bugünkü Aktivite'],
  'Recent Activity': ['Recent Activity','وروستی فعالیت','فعالیت اخیر','حالیہ سرگرمی','النشاط الأخير','हाल की गतिविधि','Actividad reciente','Activité récente','Son Aktivite'],
  'Top Customer Dues': ['Top Customer Dues','د پېرودونکو لوی پورونه','بیشترین بدهی مشتریان','سب سے زیادہ کسٹمر بقایا','أعلى مستحقات العملاء','शीर्ष ग्राहक बकाया','Principales deudas de clientes','Principales dettes clients','En Yüksek Müşteri Borçları'],
  'Top Salesman Dues': ['Top Salesman Dues','د خرڅوونکو لوی پورونه','بیشترین بدهی فروشندگان','سب سے زیادہ سیلز مین بقایا','أعلى مستحقات المندوبين','शीर्ष सेल्समैन बकाया','Principales deudas de vendedores','Principales dettes vendeurs','En Yüksek Satış Elemanı Borçları'],
  'Business Position': ['Business Position','د کاروبار حالت','وضعیت کسب‌وکار','کاروباری پوزیشن','وضع النشاط','व्यवसाय स्थिति','Posición del negocio','Situation de l’entreprise','İşletme Durumu'],
  'No data.': ['No data.','معلومات نشته.','داده‌ای نیست.','کوئی ڈیٹا نہیں۔','لا توجد بيانات.','कोई डेटा नहीं।','Sin datos.','Aucune donnée.','Veri yok.'],
};
